#language: python
#
#python: "3.9"
#dist: xenial
#sudo: true
#install:
#  - pip install -r requirements.txt
## command to run tests
##script:
##  - pytest

{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "python": [
    "3.9.4"
  ],
  "install": [
    "pip install -r requirements.txt"
  ],
  "script": [
    "pytest"
  ]
}